version: '3.3'
# $ docker pull 3.12.0-rc.1-management
#it $ docker run --rm -it -p 15672:15672 -p 5672:5672 rabbitmq:3.12.0-rc.1-management

services:
  rabbitmq:
    image: rabbitmq:3.12.0-rc.1-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672